http:
  base_url: !secret http_base_url

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.js

custom_updater:
  track: dev
  card_url: !secret custom_ui_url

hacs:
  token: !secret hacs_token